version: '3'

services:

  nc:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - nextcloud_network
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
    volumes:
      - nextcloud:/var/www/html

  db:
    image: mariadb
    container_name: nextcloud_db
    restart: unless-stopped
    networks:
      - nextcloud_network
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - db:/var/lib/mysql

  locust:
    image: locustio/locust
    container_name: locust
    networks:
      - nextcloud_network
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
      - ./test_data:/test_data
    command: -f /mnt/locust/locustest.py -H http://nextcloud:80 
    environment:
      - LOCUST_MODE=standalone
      - LOCUST_TARGET_URL=http://nextcloud

volumes:
  nextcloud:
  db:

networks:
  nextcloud_network: