version: '3'

services:
  nc:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - nextcloud_network
    ports:
      - "8080:80"
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - SQLITE_DATABASE=nextcloud
      - SQLITE_DB_DIR=/var/www/html/data
    volumes:
      - nextcloud_data:/var/www/html

volumes:
  nextcloud_data:

networks:
  nextcloud_network: